package:
    name: dime-server
    version: "0.0.1"
source:
    git_url: https://github.com/zmalkmus/dime-server.git
requirements:
    build:
        - make
        - gcc
        - gnuconfig
        - automake
        - autoconf
        - libtool
        - cmake
        - {{ compiler('c') }}
        - jansson >=2.14
        - openssl
        - zlib
        - libev >=4.24
    host:
        - libtool
        - zlib
        - openssl
        - jansson >=2.13
        - libev >=4.24
    run:
        - libev >=4.24
        - zlib
        - openssl
        - jansson >=2.14
about:
  home: https://github.com/CURENT/dime
  license: GPL-3.0
  summary: LTB DiME - Distributed Messaging Environment for CURENT Large-scale Testbed
