package:
    name: dime-server
    version: "0.0.1"
source:
    git_url: https://github.com/zmalkmus/dime-server.git
requirements:
    build:
        - make
        - gcc
        - {{ compiler('c') }}
    host:
        - libtool
        - setuptools
        - zlib
        - openssl
        - jansson >=2.14
        - libev
    run:
        - libev
        - zlib
        - openssl
        - jansson >=2.14
about:
  home: https://github.com/CURENT/dime
  license: GPL-3.0
  summary: LTB DiME - Distributed Messaging Environment for CURENT Large-scale Testbed
